DROP DATABASE IF EXISTS wildcircus;
CREATE DATABASE IF NOT EXISTS wildcircus;
USE wildcircus;

DROP TABLE IF EXISTS joke, picture;

CREATE TABLE joke (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  country VARCHAR(100) NOT NULL,
  joke VARCHAR(255) NOT NULL
);

CREATE TABLE picture (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL
);